# Generated by Django 2.2.8 on 2019-12-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
